<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input</name>
   <tag></tag>
   <elementGuidId>aac4297e-2a11-4a69-ae41-5d94fa3cbe00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;root&quot;]/div[2]/div/div[2]/div/div[2]/div/div[2]/input[count(. | //*[@placeholder = 'Cari' and @type = 'text']) = count(//*[@placeholder = 'Cari' and @type = 'text'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;root&quot;]/div[2]/div/div[2]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>e5f99581-ce96-4f84-a1ef-6ab46092b78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari</value>
      <webElementGuid>0ee5434f-faf1-4bd6-ade3-09b94519a341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>68a88d80-8919-45c3-916c-7635ceb47bee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
