<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kirim Email</name>
   <tag></tag>
   <elementGuidId>92490ab7-f5c8-46e6-a121-3c4972684926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kirimEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='kirimEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>14ea1286-219b-4cf0-ab24-cab095d8ea60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>426e6352-b8ac-46bd-82ca-d20ea72ab323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kirimEmail</value>
      <webElementGuid>72c288db-99ba-47e2-a43e-66945d00066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim Email!</value>
      <webElementGuid>80e2f7ab-7a2b-40e7-bde2-c5d35128400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kirimEmail&quot;)</value>
      <webElementGuid>02256563-f154-4247-af1a-2148a8755d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='kirimEmail']</value>
      <webElementGuid>45d55814-797f-4a0b-a341-be6f52dd31eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[7]/form/button</value>
      <webElementGuid>cbe92246-0d01-4df3-bf98-6d67b3f69c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gagal'])[1]/following::button[1]</value>
      <webElementGuid>9edd7cb0-b232-41e6-8afb-0b5324d0ad4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunas'])[1]/following::button[2]</value>
      <webElementGuid>3949f656-366c-49b3-9505-4f24a01d6a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'kirimEmail', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>1eeac05e-436f-4ac8-b515-c80daaebd97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kirim Email!']/parent::*</value>
      <webElementGuid>84e66008-4a5b-4a08-9f74-01914ccebdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>4f58d6a2-1b69-4368-a6e5-afd7755e6dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'kirimEmail' and (text() = 'Kirim Email!' or . = 'Kirim Email!')]</value>
      <webElementGuid>e0bb28d2-61e0-4f1e-9915-78c96592ef73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
