<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>check_email</name>
   <tag></tag>
   <elementGuidId>e0fefc41-b95a-4945-8695-623dc65b4fc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div[3]/div/div[2]/div[3]/h6[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>0fbb5495-bf33-4728-ad48-5a087f3489b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>270e40ad-f609-4cce-b1f3-2548a42d0ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mg1671687299954@gmail.com</value>
      <webElementGuid>2c9d83c5-7a80-44e6-9f4a-13cd25ad6cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content mb-5-content&quot;]/div[@class=&quot;detailHeader d-flex&quot;]/div[@class=&quot;row-detail w-55&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;head-invoice&quot;]/h6[@class=&quot;judul&quot;]</value>
      <webElementGuid>ae320fc6-ee71-4941-8228-580cf1fc1780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[3]/div/div[2]/div[3]/h6[2]</value>
      <webElementGuid>398d1439-464c-497d-92c2-b24ba2ff702f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AVANGER'])[2]/following::h6[1]</value>
      <webElementGuid>1468878f-d545-4e28-989d-20af6d8ef6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[4]/following::h6[2]</value>
      <webElementGuid>f1afeffc-a845-43e1-8440-61b292d0c6ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk :'])[1]/preceding::h6[3]</value>
      <webElementGuid>f42f3450-bf4e-4c01-af55-f6cb0b1a3202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[1]/preceding::h6[3]</value>
      <webElementGuid>2efcc837-e0ac-436a-9a32-8665617fc761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mg1671687299954@gmail.com']/parent::*</value>
      <webElementGuid>810c22f1-5366-4b92-8b21-c9f086a7da69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h6[2]</value>
      <webElementGuid>1e5c6e41-9343-479f-b875-17e9dd36decb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = 'mg1671687299954@gmail.com' or . = 'mg1671687299954@gmail.com')]</value>
      <webElementGuid>528c76b5-8c3f-4047-a791-eaf62607e8cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
