<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Mmanusia</name>
   <tag></tag>
   <elementGuidId>554887b0-4a1b-46d9-8d2b-b7bd3a1defca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div[2]/div/div[3]/div[6]/a/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f785ad01-2b9c-4483-afcb-bfa31f6a6b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datas d-flex align-items-center</value>
      <webElementGuid>3f52d8ad-469f-4baa-8bde-c6273043a913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mmanusia</value>
      <webElementGuid>2637c4f1-1ba8-4908-aefa-015c706c3dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content&quot;]/div[2]/div[@class=&quot;riwayat-list__container&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[6]/a[1]/div[@class=&quot;container-list d-flex flex-row align-items-center&quot;]/div[@class=&quot;datas d-flex align-items-center&quot;]</value>
      <webElementGuid>6cd309e3-af71-406f-8111-b280feffd020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[2]/div/div[3]/div[6]/a/div/div</value>
      <webElementGuid>06fcb6ca-da53-4e1b-8d5a-e7e33bd983e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0,00'])[4]/following::div[4]</value>
      <webElementGuid>349602ad-816d-4aa2-a9cc-95900ca39438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[4]/following::div[5]</value>
      <webElementGuid>70cbb717-5ad9-4acf-9877-d5fe14a4affb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='manusia']/parent::*</value>
      <webElementGuid>75f695a1-b871-4083-81fe-0464af86af14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/div</value>
      <webElementGuid>223d4baf-d480-4383-93a6-87496c353e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Mmanusia' or . = 'Mmanusia')]</value>
      <webElementGuid>83be2f78-a804-40b8-af08-2c8eb0cf9aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
