<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Berhasil</name>
   <tag></tag>
   <elementGuidId>9efbccb2-8e8a-4df5-876e-785e22479fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div[2]/div/div[3]/div[6]/a/div/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'badge-berhasil w-auto' and (text() = 'Berhasil' or . = 'Berhasil')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>359bb7f8-031f-4cda-9634-6ce34c2cc093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge-berhasil w-auto</value>
      <webElementGuid>396d8c34-0887-4c1a-870a-08da56631f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berhasil</value>
      <webElementGuid>cb1f38d8-0668-4867-8229-ebb0c140db1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content&quot;]/div[2]/div[@class=&quot;riwayat-list__container&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[6]/a[1]/div[@class=&quot;container-list d-flex flex-row align-items-center&quot;]/div[@class=&quot;datas d-flex justify-content-center&quot;]/div[@class=&quot;badge-berhasil w-auto&quot;]</value>
      <webElementGuid>7a915f18-35f1-4aee-a36b-6f843424a8ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[2]/div/div[3]/div[6]/a/div/div[6]/div</value>
      <webElementGuid>52f87b50-652a-44b2-bd64-250d472e3ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 8.000,00'])[1]/following::div[2]</value>
      <webElementGuid>24ddd04a-b7ac-4929-9685-b7abd3002086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::div[3]</value>
      <webElementGuid>793fc0f1-5d4b-4aa4-9420-6b3e1dea88f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;- Prev'])[1]/preceding::div[1]</value>
      <webElementGuid>886ce54b-3382-4817-a60d-b4a68e475bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next ->'])[1]/preceding::div[1]</value>
      <webElementGuid>125111d7-9dc6-4321-8b49-f38bf9ca4834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/div[6]/div</value>
      <webElementGuid>225eabc2-0f31-4456-b833-45e7ebcd6a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Berhasil' or . = 'Berhasil')]</value>
      <webElementGuid>ab3b32f8-3128-4c51-93c8-999339d34d57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
