<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Gagal</name>
   <tag></tag>
   <elementGuidId>f2c768f6-4be1-4a0e-a801-787335cec474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.badge-gagal.w-auto</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'badge-gagal w-auto' and (text() = 'Gagal' or . = 'Gagal')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d18fd56e-89c5-4c73-b7f2-c68ce40a8c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>badge-gagal w-auto</value>
      <webElementGuid>2fbc8589-15ec-4c8d-9e64-83910983c5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gagal</value>
      <webElementGuid>18d3c70d-31d8-4856-bfed-0ed9d9b067e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content mb-5-content&quot;]/div[2]/div[@class=&quot;badge-gagal w-auto&quot;]</value>
      <webElementGuid>31c25bff-e21a-406b-af20-0d1f43ffc09d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>5982449d-633b-4533-a24c-d57c74fff75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::div[2]</value>
      <webElementGuid>905651cb-16f8-4d5d-b04a-803c8c0ef31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mg'])[1]/following::div[4]</value>
      <webElementGuid>88b95a1d-de19-4ece-bd9e-bc903f72e082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice'])[2]/preceding::div[1]</value>
      <webElementGuid>6b27daa6-5d60-4d1d-b9f9-dd5f9ad5b5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Gagal']/parent::*</value>
      <webElementGuid>c5480332-e3e3-4c59-bd86-593e5b89856c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div[2]/div</value>
      <webElementGuid>16774524-bd09-4adb-99c6-a2860f209909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Gagal' or . = 'Gagal')]</value>
      <webElementGuid>28b4c4b4-01d4-48f1-bde0-380e865197a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
