<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h6_2022-12-22</name>
   <tag></tag>
   <elementGuidId>b18fc519-f14c-484b-ae45-793d971161df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div[4]/div/div[2]/div[3]/h6[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>3f62732c-957d-4aa2-b121-af99a8988714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>judul</value>
      <webElementGuid>38e551d9-b8e1-4774-bdb6-d35f6df014dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022-12-22</value>
      <webElementGuid>e3b8b519-3962-413d-aa51-a8d5987f4cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content mb-5-content&quot;]/div[@class=&quot;detailHeader d-flex&quot;]/div[@class=&quot;row-detail w-55&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;head-invoice&quot;]/h6[@class=&quot;judul&quot;]</value>
      <webElementGuid>02aeac36-d624-46dc-a5f6-7e0ef1674a35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[4]/div/div[2]/div[3]/h6[4]</value>
      <webElementGuid>7428a758-c3ae-4747-a557-fcfc2c8142f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mg1671687299954@gmail.com'])[1]/following::h6[2]</value>
      <webElementGuid>b29b677b-775e-491c-80ed-ff4aa2abb4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AVANGER'])[2]/following::h6[3]</value>
      <webElementGuid>e21e929f-2a86-4a99-95ca-5a4f645951cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk :'])[1]/preceding::h6[1]</value>
      <webElementGuid>993ef8f0-2fb2-4856-b865-4c65176f5128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[1]/preceding::h6[1]</value>
      <webElementGuid>c7a2382e-2ede-4937-a0d3-e479a8acbaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022-12-22']/parent::*</value>
      <webElementGuid>08dd738f-268b-433c-8f20-16ba20484b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h6[4]</value>
      <webElementGuid>89c9d2fd-39b9-4618-9680-4eda7c80326e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h6[(text() = '2022-12-22' or . = '2022-12-22')]</value>
      <webElementGuid>1798cd8d-7fa2-4cd7-acdf-02d24bb5e6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
