<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Diskon_diskon</name>
   <tag></tag>
   <elementGuidId>8787475a-e38f-43b2-8ca2-57d188882d7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;diskon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='diskon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45952a06-fd0e-4e75-ab2f-76a1bb9b7fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>93c42e34-dc5a-4f25-a6d2-ecc1eab61ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-diskon w-75</value>
      <webElementGuid>f164ab35-c850-4a8e-bc3a-a33c45cd5df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>diskon</value>
      <webElementGuid>7dabddc4-3980-4616-aa22-5bdcc7dab7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content mb-5-content&quot;]/div[@class=&quot;invoice-item__summary mt-5 d-flex justify-content-between&quot;]/div[@class=&quot;invoice-item__pricing d-flex justify-content-end flex-column gap-2&quot;]/div[@class=&quot;invoice-input_diskon d-flex justify-content-between align-items-center ms-2 me-2&quot;]/div[@class=&quot;w-25&quot;]/input[@class=&quot;input-diskon w-75&quot;]</value>
      <webElementGuid>dd1f14a7-15bb-427f-8e13-35eb95a1a094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='diskon']</value>
      <webElementGuid>b04fe038-bc2d-4bbb-941f-d34311b9271c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[5]/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>60f336f2-4bae-4bfc-8278-f19e02c7bc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>abc8a314-b8a0-4935-b4f1-1f51b436dac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'diskon']</value>
      <webElementGuid>6ca0208e-19f6-4feb-8670-8e06d46ab8ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
