<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ginap_Rekening</name>
   <tag></tag>
   <elementGuidId>32b24f00-d7e7-4a6b-bacd-df299f856976</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Account_Number&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Account_Number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f69d386f-068c-4078-93ac-4fbbcf3aef08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1ca490d-0b1e-4fa9-a5cf-89239807c5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Rekening Bank</value>
      <webElementGuid>0b624b60-afd8-4b17-bb9f-0dd5ee1c3784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input mt-7</value>
      <webElementGuid>3d931ebf-e440-4354-a1a7-c90b07e2eb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Account_Number</value>
      <webElementGuid>ea0088d8-d9c4-4560-8cb4-354d83b3910d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Wrap&quot;]/div[@class=&quot;containerLogin d-flex flex-column justify-content-center&quot;]/form[@class=&quot;register-business__form&quot;]/input[@class=&quot;input mt-7&quot;]</value>
      <webElementGuid>f1aace3f-28e6-470b-9f99-1d472dbefcda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Account_Number']</value>
      <webElementGuid>a928a6af-5058-4f66-b77c-5c9d54ad79d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/input[4]</value>
      <webElementGuid>289e3d8f-1f3d-4bb4-891a-daa92edb6c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>2b9f2b4a-d867-40ac-9989-6231e3c95b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Rekening Bank' and @name = 'Account_Number']</value>
      <webElementGuid>2263a572-aa77-4d8c-926e-af9b79dc482c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
