<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lupa kata sandi</name>
   <tag></tag>
   <elementGuidId>ed1557a0-6020-4cef-905f-945002ac5fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.forgetPassword.mt-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/form/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>22231933-a36f-4149-af77-e64f9f035d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/forget-password</value>
      <webElementGuid>d71a8340-4613-4c90-8f49-c5886d00e4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>forgetPassword mt-1</value>
      <webElementGuid>f47d77c7-329f-49b6-997c-b912b4a25f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lupa kata sandi?</value>
      <webElementGuid>76224892-fece-4b35-8a94-9eb424baad87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;Wrap&quot;]/div[@class=&quot;containerLogin d-flex flex-column justify-content-center&quot;]/form[@class=&quot;containerInput&quot;]/a[@class=&quot;forgetPassword mt-1&quot;]</value>
      <webElementGuid>30ded4a3-f4b2-49c2-863d-1fdafd85f849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/form/a</value>
      <webElementGuid>d3bd9a6f-e7a2-4cf8-b4bc-516f6e1deac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lupa kata sandi?')]</value>
      <webElementGuid>923fcba2-e2f6-40cb-bef3-10e39c26e2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ginap'])[1]/following::a[1]</value>
      <webElementGuid>48a78289-d3ec-4277-9857-c5022f26242c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/preceding::a[1]</value>
      <webElementGuid>11151867-6d73-4d23-a380-6af026d6788a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atau masuk dengan'])[1]/preceding::a[1]</value>
      <webElementGuid>56963546-5a61-4306-a961-959c2c1b3361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lupa kata sandi?']/parent::*</value>
      <webElementGuid>b46df79c-675d-446c-a7c2-55515beb8f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/forget-password')]</value>
      <webElementGuid>d240137b-9152-4a26-9ec4-e7899e65ed9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>760da340-7227-42ca-99ae-3b53be1a0a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/forget-password' and (text() = 'Lupa kata sandi?' or . = 'Lupa kata sandi?')]</value>
      <webElementGuid>b1be8ecc-e9b2-4390-a39f-40f2f7034fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
