<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Masuk</name>
   <tag></tag>
   <elementGuidId>6bd5ff25-18f5-4690-b595-af620a32a321</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'buttonMasuk' and (text() = 'Masuk' or . = 'Masuk')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;buttonDaftar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonMasuk</value>
      <webElementGuid>0a169659-3a9b-4313-bdaf-b03aa7c85edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>1c45b810-5a0b-4620-8430-1dc42cc17f38</webElementGuid>
   </webElementProperties>
</WebElementEntity>
