<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete-icon_item</name>
   <tag></tag>
   <elementGuidId>3a11482a-be08-4d61-8914-82415969e2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.bi.bi-trash3-fill.delete-icon__item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/div/div[3]/div[2]/div[5]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4b951691-3a71-47ee-acca-6afe689b5b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-trash3-fill delete-icon__item</value>
      <webElementGuid>21832b9e-e30a-4c8b-a632-e560a7b0136f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>ee3757f9-112e-441d-bcb3-bb1e4e1cd26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container-fluid p-0&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column w-100&quot;]/div[@class=&quot;container-content&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;container-list d-flex flex-row align-items-center&quot;]/div[@class=&quot;pelanggan-hapus&quot;]/i[@class=&quot;bi bi-trash3-fill delete-icon__item&quot;]</value>
      <webElementGuid>0e839c83-090b-4dff-8d5d-2948f6c2b0ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/div/div[3]/div[2]/div[5]/i</value>
      <webElementGuid>6e6fcc2c-9601-438c-bc11-2e29f9e281a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>b2e218d3-8531-487a-a392-c35683cedef4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
