<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UserID</name>
   <tag></tag>
   <elementGuidId>738b8d5e-2996-4891-9dd1-51522f144837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;exampleModal&quot;]/div/div/div[2]/form/div[1]/ul/li[${id}]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@class = 'list-group-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item</value>
      <webElementGuid>8e1fb86d-414d-4a3a-bdeb-6b92bc4c0d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fef9cf5f-4e48-4ce1-a848-6b139a71d7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${id}</value>
      <webElementGuid>c974e306-3dec-4776-bee9-79324c2d2dc4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
